mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
mkfile_dir := $(dir $(mkfile_path))

all:

frontend-dev:
	cd $(mkfile_dir)/frontend; npm run dev;

backend-dev:
	cd $(mkfile_dir)/backend; uvicorn main:app --reload;

# Build Docker Images
# todo update the image names
build-frontend:
	docker build --network=host -t catsmao/frontend $(mkfile_dir)/frontend

build-backend:
	docker build --network=host -t catsmao/backend $(mkfile_dir)/backend

build-frontend-no-cache:
	docker build --no-cache --network=host -t catsmao/frontend $(mkfile_dir)/frontend

build-backend-no-cache:
	docker build --no-cache --network=host -t catsmao/backend $(mkfile_dir)/backend

build-docker:build-frontend-no-cache build-backend-no-cache


# Docker Commands
# todo update the image names
push-dockers:
	docker push catsmao/frontend:latest
	docker push catsmao/backend:latest

run-frontend:
	 docker run -it --rm -d -p 3000:3000 --name frontend catsmao/frontend

run-backend:
	 docker run -it --rm -d -p 8000:8000 --name backend catsmao/backend

run-all-docker:
	docker-compose up -d

stop-all-docker:
	docker-compose down