version: "3"
services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    volumes:
      - ./config/:/mosquitto/config/:ro
      - ./log/:/mosquitto/log/
      - ./data/:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001

  mqtt-bridge:
    image: registry.gitlab.com/maomaocake/smart-farm/mqtt-bridge:latest
    ports:
      - 5000:5000
    env_file:
      - http-mqtt-bridge.env
    depends_on:
      - mqtt-broker
    links:
      - mqtt-broker:mqtt-broker

  reverse-proxy:
    image: traefik:v2.8
    # Enables the web UI and tells Traefik to listen to docker
    # Disable webUI in production
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - frontend
      - backend
    links:
      - database:db
      - mqtt-bridge:bridge

  frontend:
    container_name: frontend
    image: registry.gitlab.com/maomaocake/smart-farm/frontend:latest
    restart: unless-stopped
    expose:
      - 3000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.entrypoints=http'
      - "traefik.http.routers.frontend.rule=Host(`smart-farm.jirapongpansak.com`)"
    depends_on:
      - backend

  backend:
    container_name: backend
    image: registry.gitlab.com/maomaocake/smart-farm/backend:latest
    restart: unless-stopped
    expose:
      - 8000
    env_file:
      - backend.env
    links:
      - database:db
      - mqtt-bridge:bridge
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.entrypoints=http'
      - "traefik.http.routers.backend.rule=Host(`smart-farm.jirapongpansak.com`) && PathPrefix(`/api/`)"
    depends_on:
      - backend-worker
      - database

  backend-worker:
    container_name: worker
    image: registry.gitlab.com/maomaocake/smart-farm/backend-worker:latest
    restart: unless-stopped
    expose:
      - 8000
    env_file:
      - backend.env
    links:
      - database:db
      - mqtt-bridge:bridge
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.worker.entrypoints=http'
    depends_on:
      - mqtt-bridge
      - database

  mqtt2db:
    container_name: mqtt2db
    image: registry.gitlab.com/maomaocake/smart-farm/mqtt2db:latest
    restart: unless-stopped
    env_file:
      - mqtt2db.env
    depends_on:
      - mqtt-broker
      - mongodb

  mongodb:
    image: mongo:4.2.1 # need to specify the version to prevent code corruption
    environment: # variable of the server or OS
      MONGO_INITDB_ROOT_USERNAME: touch
      MONGO_INITDB_ROOT_PASSWORD: touchja
    ports:
      - "27017:27017"

  database:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    env_file:
      - mysql.env
#    labels:
#      - 'traefik.enable=true'
    ports:
      - "3306:3306"
    volumes:
      - smart-farm-db:/var/lib/mysql
volumes:
  smart-farm-db: