from enum import Enum

class Role(Enum):
    ADMIN = "ADMIN"
    USER = "USER"
    VIEWER = 'VIEWER'


class HardwareType(str, Enum):
    LIGHT = "LIGHT"
    AC = "AC"
    CO2_SENSOR = "CO2_SENSOR"
    CO2_CONTROLLER = "CO2_CONTROLLER"
    DEHUMIDIFIER = "DEHUMIDIFIER"
    HUMIDITY_SENSOR = "HUMIDITY_SENSOR"
    TEMPERATURE_SENSOR = "TEMPERATURE_SENSOR"
    WATERING = "WATERING"
