from enum import Enum

class Role(Enum):
    ADMIN = "ADMIN"
    USER = "USER"
    VIEWER = 'VIEWER'

class ESPType(str, Enum):
    SENSOR = "SENSOR"
    CO2_CONTROLLER = "CO2_CONTROLLER"
    LIGHT_CONTROLLER = "LIGHT_CONTROLLER"
    AC_CONTROLLER = "AC_CONTROLLER"
    DEHUMIDIFIER_CONTROLLER = "DEHUMIDIFIER_CONTROLLER"
    WATERING_SYSTEM = "WATERING_SYSTEM"

class HardwareType(str, Enum):
    LIGHT = "LIGHT"
    AC = "AC"
    CO2_SENSOR = "CO2_SENSOR"
    CO2_CONTROLLER = "CO2_CONTROLLER"
    DEHUMIDIFIER = "DEHUMIDIFIER"
    HUMIDITY_SENSOR = "HUMIDITY_SENSOR"
    TEMPERATURE_SENSOR = "TEMPERATURE_SENSOR"
    WATERING = "WATERING"

class System(str, Enum):
    USERNAME = "mqtt2db"
