name: Docker Image CI

on:
  push:
    branches: [ "feat/fix-CI-build" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Into GitLab Registry
      run: docker login registry.gitlab.com -u maomaocake -p ${{ secrets.GITLAB_REGISTRY_SECRET }}
    - name: Build the frontend Docker image
      run: docker build frontend --file frontend/Dockerfile --tag registry.gitlab.com/maomaocake/smart-farm/frontend:latest-test
    - name: Upload image to GitLab CR
      run: docker push registry.gitlab.com/maomaocake/smart-farm/frontend:latest-test
